# Generated by Django 4.1.5 on 2023-01-27 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner_img',
            field=models.ImageField(default='', upload_to='banner_images'),
        ),
    ]
