# Generated by Django 4.1.5 on 2023-01-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_img',
            field=models.ImageField(default='blank-profile-picture.png', upload_to='banner_images'),
        ),
    ]
