# Generated by Django 4.1.5 on 2023-01-28 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_profile_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner_img',
            field=models.ImageField(default='blog-detailfull.jpg', upload_to='banner_images'),
        ),
    ]
