# Generated by Django 4.1.5 on 2023-01-30 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
